-- Analytics tables for normalized war/CWL/attack history.
-- Run after schema.sql in the dedicated Discord Supabase project.

create table if not exists war_attacks (
  id bigint generated by default as identity primary key,
  war_key text not null,
  clan_tag text not null,
  attacker_tag text not null,
  attacker_name text,
  defender_tag text,
  defender_name text,
  stars int,
  destruction_percentage int,
  order_no int,
  attack_time timestamptz,
  data jsonb not null,
  unique(war_key, attacker_tag, order_no)
);
create index if not exists war_attacks_war_idx on war_attacks(war_key);
create index if not exists war_attacks_attacker_idx on war_attacks(attacker_tag, attack_time desc);

create table if not exists war_members (
  id bigint generated by default as identity primary key,
  war_key text not null,
  clan_tag text not null,
  player_tag text not null,
  player_name text,
  map_position int,
  attacks_available int,
  attacks_used int,
  stars_earned int,
  destruction_percentage numeric,
  data jsonb not null,
  unique(war_key, player_tag)
);
create index if not exists war_members_player_idx on war_members(player_tag);

create table if not exists cwl_wars (
  id bigint generated by default as identity primary key,
  season_key text not null,
  war_tag text not null unique,
  clan_tag text not null,
  opponent_clan_tag text,
  opponent_name text,
  state text,
  data jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists cwl_wars_season_idx on cwl_wars(season_key);

create or replace view player_war_summary as
select
  wm.player_tag,
  max(wm.player_name) as player_name,
  count(*) as wars,
  sum(coalesce(wm.attacks_used, 0)) as attacks_used,
  sum(coalesce(wm.attacks_available, 0)) as attacks_available,
  sum(coalesce(wm.stars_earned, 0)) as stars,
  round(avg(coalesce(wm.destruction_percentage, 0)), 2) as avg_destruction
from war_members wm
group by wm.player_tag;
