-- Ponyo Supabase schema
-- Run this entire file once in Supabase SQL Editor for the Ponyo database.
-- It is intentionally independent from the legacy coc-watcher database.

create extension if not exists pgcrypto;

create table if not exists public.ai_chat (
  index_no bigint generated by default as identity primary key,
  date_time timestamptz not null default now(),
  messenger text not null,
  context jsonb
);

create table if not exists public.clan_info (
  index_no bigint generated by default as identity primary key,
  player_id text not null unique,
  name text not null,
  role text,
  th integer,
  lvl integer,
  trophies integer,
  troops_donated integer,
  troops_received integer,
  last_active timestamptz,
  date_time timestamptz not null default now(),
  data jsonb
);

create table if not exists public.clan_info_snap (
  index_no bigint generated by default as identity primary key,
  date_time timestamptz not null default now(),
  player_id text not null,
  name text,
  role text,
  th integer,
  lvl integer,
  trophies integer,
  troops_donated integer,
  troops_received integer,
  data jsonb
);

create table if not exists public.cw_session (
  index_no bigint generated by default as identity primary key,
  cw_uid text not null unique,
  opponent_clan_name text,
  opponent_clan_id text,
  size integer,
  battle_start timestamptz,
  battle_end timestamptz,
  result text,
  our_clan_score integer,
  opponent_clan_score integer,
  our_clan_destruction numeric,
  opponent_clan_destruction numeric,
  participants_size integer,
  our_participants jsonb,
  opponent_participants jsonb,
  data jsonb
);

create table if not exists public.cw_session_participants (
  index_no bigint generated by default as identity primary key,
  cw_uid text not null,
  player_name text,
  player_id text not null,
  attacks_used integer not null default 0,
  attacks_available integer not null default 2,
  stars_scored integer not null default 0,
  destruction_caused numeric not null default 0,
  cw_attack_uid text,
  player_map_position integer,
  battle_start timestamptz,
  battle_end timestamptz,
  size integer,
  data jsonb,
  unique (cw_uid, player_id)
);

create table if not exists public.cw_attacklog (
  index_no bigint generated by default as identity primary key,
  cw_attack_uid text not null unique,
  attacker_clan_name text,
  attacker_clan_id text,
  attacker_name_with_map_position text,
  defender_name_with_map_position text,
  star_scored integer,
  destruction_caused numeric,
  attacking_date_time timestamptz,
  attacker_id text,
  cw_uid text not null,
  data jsonb
);

create table if not exists public.cwl_seasons (
  index_no bigint generated by default as identity primary key,
  generated_cwl_id text not null unique,
  battle_start timestamptz,
  battle_end timestamptz,
  stars_scored integer,
  clan_participants_no integer,
  data jsonb
);

create table if not exists public.cwl_season_participants (
  index_no bigint generated by default as identity primary key,
  cwl_day_uid text not null,
  player_name text,
  player_id text not null,
  attacks_used integer not null default 0,
  attacks_available integer not null default 1,
  stars_scored integer not null default 0,
  destruction_caused numeric not null default 0,
  cwl_attack_uid text,
  player_map_position integer,
  battle_day_start timestamptz,
  battle_day_end timestamptz,
  size integer,
  data jsonb,
  unique (cwl_day_uid, player_id)
);

create table if not exists public.cwl_daywise_attacklog (
  index_no bigint generated by default as identity primary key,
  generated_cwl_day_id text not null unique,
  battle_day integer,
  battle_start timestamptz,
  battle_end timestamptz,
  size integer,
  opponent_clan_name text,
  opponent_clan_id text,
  our_clan_score integer,
  opponent_clan_score integer,
  our_participants jsonb,
  opponent_participants jsonb,
  data jsonb
);

create table if not exists public.cwl_attacklog (
  index_no bigint generated by default as identity primary key,
  generated_cwl_attack_uid text not null unique,
  battle_day integer,
  attacker_clan_name text,
  attacker_name_with_map_position text,
  defender_name_with_map_position text,
  star_scored integer,
  destruction_caused numeric,
  attacking_date_time timestamptz,
  attacker_id text,
  cwl_day_uid text not null,
  data jsonb
);

create table if not exists public.capital_raid_season (
  index_no bigint generated by default as identity primary key,
  generated_uid text not null unique,
  battle_start timestamptz,
  battle_end timestamptz,
  total_loot bigint,
  raids_won integer,
  total_attacks integer,
  participants_no integer,
  absentees_no integer,
  participants_name jsonb,
  absentees_name jsonb,
  data jsonb
);

create table if not exists public.capital_raid_participants (
  index_no bigint generated by default as identity primary key,
  capital_raid_uid text not null,
  player_name text,
  player_id text not null,
  attacks_used integer not null default 0,
  attacks_available integer not null default 5,
  total_loot_gained bigint not null default 0,
  capital_raid_attack_uid text,
  capital_raid_start timestamptz,
  capital_raid_end timestamptz,
  data jsonb,
  unique (capital_raid_uid, player_id)
);

create table if not exists public.capital_raid_attacklog (
  index_no bigint generated by default as identity primary key,
  generated_uid text not null unique,
  raid_no integer,
  clan_name text,
  district_name text,
  attacker_name text,
  star_scored integer,
  destruction_caused numeric,
  loot_gained bigint,
  attacking_date_time timestamptz,
  attacker_id text,
  capital_raid_uid text not null,
  data jsonb
);

create table if not exists public.ai_answers (
  id uuid primary key,
  guild_id text,
  channel_id text,
  user_id text not null,
  provider text not null,
  question text not null,
  full_answer text not null,
  message_id text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create table if not exists public.ai_conversations (
  index_no bigint generated by default as identity primary key,
  guild_id text,
  channel_id text,
  user_id text not null,
  provider text not null,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists idx_clan_info_name on public.clan_info(name);
create index if not exists idx_clan_info_snap_player_time on public.clan_info_snap(player_id, date_time desc);
create index if not exists idx_cw_participants_war on public.cw_session_participants(cw_uid);
create index if not exists idx_cw_participants_player on public.cw_session_participants(player_id);
create index if not exists idx_cw_attacklog_war_time on public.cw_attacklog(cw_uid, attacking_date_time);
create index if not exists idx_cwl_participants_day on public.cwl_season_participants(cwl_day_uid);
create index if not exists idx_cwl_participants_player on public.cwl_season_participants(player_id);
create index if not exists idx_cwl_attacklog_day_time on public.cwl_attacklog(cwl_day_uid, attacking_date_time);
create index if not exists idx_capital_participants_season on public.capital_raid_participants(capital_raid_uid);
create index if not exists idx_capital_participants_player on public.capital_raid_participants(player_id);
create index if not exists idx_capital_attacklog_season_time on public.capital_raid_attacklog(capital_raid_uid, attacking_date_time);
create index if not exists idx_ai_answers_user_expiry on public.ai_answers(user_id, expires_at);
create index if not exists idx_ai_conversations_user_channel_expiry on public.ai_conversations(user_id, guild_id, channel_id, expires_at, created_at desc);

alter table public.ai_chat enable row level security;
alter table public.clan_info enable row level security;
alter table public.clan_info_snap enable row level security;
alter table public.cw_session enable row level security;
alter table public.cw_session_participants enable row level security;
alter table public.cw_attacklog enable row level security;
alter table public.cwl_seasons enable row level security;
alter table public.cwl_season_participants enable row level security;
alter table public.cwl_daywise_attacklog enable row level security;
alter table public.cwl_attacklog enable row level security;
alter table public.capital_raid_season enable row level security;
alter table public.capital_raid_participants enable row level security;
alter table public.capital_raid_attacklog enable row level security;
alter table public.ai_answers enable row level security;
alter table public.ai_conversations enable row level security;

do $$
begin
  execute 'drop policy if exists ponyo_read_ai_chat on public.ai_chat';
  execute 'drop policy if exists ponyo_read_clan_info on public.clan_info';
  execute 'drop policy if exists ponyo_read_clan_info_snap on public.clan_info_snap';
  execute 'drop policy if exists ponyo_read_cw_session on public.cw_session';
  execute 'drop policy if exists ponyo_read_cw_participants on public.cw_session_participants';
  execute 'drop policy if exists ponyo_read_cw_attacklog on public.cw_attacklog';
  execute 'drop policy if exists ponyo_read_cwl_seasons on public.cwl_seasons';
  execute 'drop policy if exists ponyo_read_cwl_participants on public.cwl_season_participants';
  execute 'drop policy if exists ponyo_read_cwl_daywise on public.cwl_daywise_attacklog';
  execute 'drop policy if exists ponyo_read_cwl_attacklog on public.cwl_attacklog';
  execute 'drop policy if exists ponyo_read_capital_seasons on public.capital_raid_season';
  execute 'drop policy if exists ponyo_read_capital_participants on public.capital_raid_participants';
  execute 'drop policy if exists ponyo_read_capital_attacklog on public.capital_raid_attacklog';
  execute 'drop policy if exists ponyo_read_ai_answers on public.ai_answers';
  execute 'drop policy if exists ponyo_read_ai_conversations on public.ai_conversations';
end $$;

create policy ponyo_read_ai_chat on public.ai_chat for select to anon using (true);
create policy ponyo_read_clan_info on public.clan_info for select to anon using (true);
create policy ponyo_read_clan_info_snap on public.clan_info_snap for select to anon using (true);
create policy ponyo_read_cw_session on public.cw_session for select to anon using (true);
create policy ponyo_read_cw_participants on public.cw_session_participants for select to anon using (true);
create policy ponyo_read_cw_attacklog on public.cw_attacklog for select to anon using (true);
create policy ponyo_read_cwl_seasons on public.cwl_seasons for select to anon using (true);
create policy ponyo_read_cwl_participants on public.cwl_season_participants for select to anon using (true);
create policy ponyo_read_cwl_daywise on public.cwl_daywise_attacklog for select to anon using (true);
create policy ponyo_read_cwl_attacklog on public.cwl_attacklog for select to anon using (true);
create policy ponyo_read_capital_seasons on public.capital_raid_season for select to anon using (true);
create policy ponyo_read_capital_participants on public.capital_raid_participants for select to anon using (true);
create policy ponyo_read_capital_attacklog on public.capital_raid_attacklog for select to anon using (true);
create policy ponyo_read_ai_answers on public.ai_answers for select to anon using (true);
create policy ponyo_read_ai_conversations on public.ai_conversations for select to anon using (true);

-- Supabase service_role bypasses RLS and is used by the sync/AI-state write paths.

-- Sync run logging (replaces the earlier practice of writing sync status into ai_chat).
create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  job text not null,
  status text not null,
  details jsonb,
  message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists idx_sync_runs_job_time on public.sync_runs(job, started_at desc);
alter table public.sync_runs enable row level security;
