create table if not exists clans (
  tag text primary key,
  data jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists players (
  tag text primary key,
  clan_tag text not null,
  name text not null,
  role text,
  town_hall_level int,
  trophies int,
  donations int,
  donations_received int,
  attack_wins int,
  defense_wins int,
  data jsonb not null,
  updated_at timestamptz not null default now()
);
create index if not exists players_clan_name_idx on players(clan_tag, name);

create table if not exists player_snapshots (
  id bigint generated by default as identity primary key,
  player_tag text not null,
  clan_tag text not null,
  captured_at timestamptz not null default now(),
  data jsonb not null
);
create index if not exists player_snapshots_player_time_idx on player_snapshots(player_tag, captured_at desc);

create table if not exists wars (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  war_key text not null unique,
  state text,
  start_time timestamptz,
  end_time timestamptz,
  data jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists wars_clan_time_idx on wars(clan_tag, end_time desc);

create table if not exists war_members (
  id bigint generated by default as identity primary key,
  war_key text not null,
  clan_tag text not null,
  player_tag text not null,
  player_name text,
  map_position int,
  attacks_available int not null default 0,
  attacks_used int not null default 0,
  stars_earned int not null default 0,
  destruction_percentage double precision not null default 0,
  data jsonb not null,
  unique(war_key, clan_tag, player_tag)
);
create index if not exists war_members_war_idx on war_members(war_key);
create index if not exists war_members_player_idx on war_members(player_tag);

create table if not exists war_attacks (
  id bigint generated by default as identity primary key,
  war_key text not null,
  clan_tag text not null,
  attacker_tag text not null,
  attacker_name text,
  defender_tag text,
  defender_name text,
  stars int,
  destruction_percentage double precision,
  order_no int,
  duration_seconds int,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique(war_key, clan_tag, attacker_tag, order_no)
);
create index if not exists war_attacks_war_idx on war_attacks(war_key, order_no);
create index if not exists war_attacks_attacker_idx on war_attacks(attacker_tag, observed_at desc);

create table if not exists cwl_attacks (
  id bigint generated by default as identity primary key,
  season_key text not null,
  war_tag text not null,
  round_no int not null,
  clan_tag text not null,
  attacker_tag text not null,
  attacker_name text,
  defender_tag text,
  defender_name text,
  stars int,
  destruction_percentage double precision,
  order_no int,
  duration_seconds int,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique(war_tag, clan_tag, attacker_tag, order_no)
);
create index if not exists cwl_attacks_season_idx on cwl_attacks(season_key, round_no);
create index if not exists cwl_attacks_attacker_idx on cwl_attacks(attacker_tag, observed_at desc);
create index if not exists cwl_attacks_opponent_idx on cwl_attacks(defender_tag, observed_at desc);

create table if not exists capital_attacks (
  id bigint generated by default as identity primary key,
  season_key text not null,
  clan_tag text not null,
  opponent_clan_tag text,
  opponent_clan_name text,
  attacker_tag text not null,
  attacker_name text,
  district_id int,
  district_name text,
  attack_number int not null,
  stars int,
  destruction_percentage double precision,
  duration_seconds int,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique(season_key, attacker_tag, district_id, attack_number, opponent_clan_tag)
);
create index if not exists capital_attacks_season_idx on capital_attacks(season_key, observed_at desc);
create index if not exists capital_attacks_attacker_idx on capital_attacks(attacker_tag, observed_at desc);
create index if not exists capital_attacks_opponent_idx on capital_attacks(opponent_clan_tag, observed_at desc);

create table if not exists cwl_seasons (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  season_key text not null unique,
  data jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists cwl_rounds (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  season_key text not null,
  round_no int not null,
  opponent_tag text,
  opponent_name text,
  state text,
  data jsonb not null,
  unique(season_key, round_no)
);

create table if not exists cwl_wars (
  id bigint generated by default as identity primary key,
  season_key text not null,
  war_tag text not null unique,
  clan_tag text not null,
  opponent_clan_tag text,
  opponent_name text,
  state text,
  data jsonb not null,
  synced_at timestamptz not null default now()
);
create index if not exists cwl_wars_season_idx on cwl_wars(season_key);

create table if not exists capital_raids (
  id bigint generated by default as identity primary key,
  clan_tag text not null,
  season_key text not null unique,
  data jsonb not null,
  synced_at timestamptz not null default now()
);

create table if not exists sync_runs (
  id bigint generated by default as identity primary key,
  job text not null,
  status text not null,
  details jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

-- Persistent Discord AI state. These rows survive Render restarts/redeploys.
create table if not exists ai_answers (
  id uuid primary key default gen_random_uuid(),
  guild_id text,
  channel_id text,
  user_id text not null,
  message_id text,
  provider text not null,
  question text not null,
  full_answer text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists ai_answers_user_time_idx on ai_answers(user_id, created_at desc);
create index if not exists ai_answers_expiry_idx on ai_answers(expires_at);

create table if not exists ai_conversations (
  id bigint generated by default as identity primary key,
  guild_id text,
  channel_id text,
  user_id text not null,
  provider text not null,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists ai_conversations_scope_time_idx on ai_conversations(guild_id, channel_id, user_id, created_at desc);
create index if not exists ai_conversations_expiry_idx on ai_conversations(expires_at);

alter table clans enable row level security;
alter table players enable row level security;
alter table player_snapshots enable row level security;
alter table wars enable row level security;
alter table war_members enable row level security;
alter table war_attacks enable row level security;
alter table cwl_attacks enable row level security;
alter table capital_attacks enable row level security;
alter table cwl_seasons enable row level security;
alter table cwl_rounds enable row level security;
alter table cwl_wars enable row level security;
alter table capital_raids enable row level security;
alter table ai_answers enable row level security;
alter table ai_conversations enable row level security;

-- AI state is backend-only. The Discord runtime already has the service-role key because it also runs the sync scheduler.
revoke all on table ai_answers from anon, authenticated;
revoke all on table ai_conversations from anon, authenticated;
grant select, insert, update, delete on table ai_answers to service_role;
grant select, insert, update, delete on table ai_conversations to service_role;

drop policy if exists "ai read clans" on clans;
drop policy if exists "ai read players" on players;
drop policy if exists "ai read snapshots" on player_snapshots;
drop policy if exists "ai read wars" on wars;
drop policy if exists "ai read war members" on war_members;
drop policy if exists "ai read war attacks" on war_attacks;
drop policy if exists "ai read cwl attacks" on cwl_attacks;
drop policy if exists "ai read capital attacks" on capital_attacks;
drop policy if exists "ai read cwl seasons" on cwl_seasons;
drop policy if exists "ai read cwl rounds" on cwl_rounds;
drop policy if exists "ai read cwl wars" on cwl_wars;
drop policy if exists "ai read capital raids" on capital_raids;

create policy "ai read clans" on clans for select to anon using (true);
create policy "ai read players" on players for select to anon using (true);
create policy "ai read snapshots" on player_snapshots for select to anon using (true);
create policy "ai read wars" on wars for select to anon using (true);
create policy "ai read war members" on war_members for select to anon using (true);
create policy "ai read war attacks" on war_attacks for select to anon using (true);
create policy "ai read cwl attacks" on cwl_attacks for select to anon using (true);
create policy "ai read capital attacks" on capital_attacks for select to anon using (true);
create policy "ai read cwl seasons" on cwl_seasons for select to anon using (true);
create policy "ai read cwl rounds" on cwl_rounds for select to anon using (true);
create policy "ai read cwl wars" on cwl_wars for select to anon using (true);
create policy "ai read capital raids" on capital_raids for select to anon using (true);
