-- Ponyo Discord AI database
-- Source of truth: Clash of Clans API.
-- Table names mirror the spreadsheet templates in /database.

create extension if not exists pgcrypto;

create table if not exists clan_info (
  index_no bigint generated by default as identity primary key,
  player_id text not null unique,
  name text not null,
  role text,
  th int,
  lvl int,
  trophies int,
  troops_donated int,
  troops_received int,
  last_active timestamptz,
  date_time timestamptz not null default now(),
  data jsonb not null default '{}'::jsonb
);
create index if not exists clan_info_name_idx on clan_info(name);
create index if not exists clan_info_role_idx on clan_info(role);

create table if not exists clan_info_snap (
  index_no bigint generated by default as identity primary key,
  date_time timestamptz not null default now(),
  player_id text not null,
  name text,
  role text,
  th int,
  lvl int,
  trophies int,
  troops_donated int,
  troops_received int,
  data jsonb not null default '{}'::jsonb
);
create index if not exists clan_info_snap_player_time_idx on clan_info_snap(player_id, date_time desc);

create table if not exists cw_session (
  index_no bigint generated by default as identity primary key,
  cw_uid text not null unique,
  opponent_clan_name text,
  opponent_clan_id text,
  size int,
  battle_start timestamptz,
  battle_end timestamptz,
  result text,
  our_clan_score int,
  opponent_clan_score int,
  our_clan_destruction double precision,
  opponent_clan_destruction double precision,
  participants_size int,
  our_participants jsonb not null default '[]'::jsonb,
  opponent_participants jsonb not null default '[]'::jsonb,
  data jsonb not null default '{}'::jsonb
);
create index if not exists cw_session_end_idx on cw_session(battle_end desc);

create table if not exists cw_session_participants (
  index_no bigint generated by default as identity primary key,
  cw_uid text not null,
  player_name text,
  player_id text not null,
  attacks_used int not null default 0,
  attacks_available int not null default 0,
  stars_scored int not null default 0,
  destruction_caused double precision not null default 0,
  cw_attack_uid text,
  player_map_position int,
  battle_start timestamptz,
  battle_end timestamptz,
  size int,
  data jsonb not null default '{}'::jsonb,
  unique(cw_uid, player_id)
);
create index if not exists cw_session_participants_war_idx on cw_session_participants(cw_uid, player_map_position);
create index if not exists cw_session_participants_player_idx on cw_session_participants(player_id, battle_end desc);

create table if not exists cw_attacklog (
  index_no bigint generated by default as identity primary key,
  cw_attack_uid text not null unique,
  attacker_clan_name text,
  attacker_clan_id text,
  attacker_name_with_map_position text,
  defender_name_with_map_position text,
  star_scored int,
  destruction_caused double precision,
  attacking_date_time timestamptz,
  attacker_id text,
  cw_uid text,
  data jsonb not null default '{}'::jsonb
);
create index if not exists cw_attacklog_cw_idx on cw_attacklog(cw_uid, attacking_date_time);
create index if not exists cw_attacklog_attacker_idx on cw_attacklog(attacker_id, attacking_date_time desc);

create table if not exists cwl_seasons (
  index_no bigint generated by default as identity primary key,
  generated_cwl_id text not null unique,
  battle_start timestamptz,
  battle_end timestamptz,
  stars_scored int not null default 0,
  clan_participants_no int not null default 0,
  data jsonb not null default '{}'::jsonb
);
create index if not exists cwl_seasons_start_idx on cwl_seasons(battle_start desc);

create table if not exists cwl_season_participants (
  index_no bigint generated by default as identity primary key,
  cwl_day_uid text not null,
  player_name text,
  player_id text not null,
  attacks_used int not null default 0,
  attacks_available int not null default 1,
  stars_scored int not null default 0,
  destruction_caused double precision not null default 0,
  cwl_attack_uid text,
  player_map_position int,
  battle_day_start timestamptz,
  battle_day_end timestamptz,
  size int,
  data jsonb not null default '{}'::jsonb,
  unique(cwl_day_uid, player_id)
);
create index if not exists cwl_participants_day_idx on cwl_season_participants(cwl_day_uid, player_map_position);
create index if not exists cwl_participants_player_idx on cwl_season_participants(player_id, battle_day_end desc);

create table if not exists cwl_daywise_attacklog (
  index_no bigint generated by default as identity primary key,
  generated_cwl_day_id text not null unique,
  battle_day int,
  battle_start timestamptz,
  battle_end timestamptz,
  size int,
  opponent_clan_name text,
  opponent_clan_id text,
  our_clan_score int,
  opponent_clan_score int,
  our_participants jsonb not null default '[]'::jsonb,
  opponent_participants jsonb not null default '[]'::jsonb,
  data jsonb not null default '{}'::jsonb
);
create index if not exists cwl_daywise_day_idx on cwl_daywise_attacklog(battle_day, battle_start desc);

create table if not exists cwl_attacklog (
  index_no bigint generated by default as identity primary key,
  generated_cwl_attack_uid text not null unique,
  battle_day int,
  attacker_clan_name text,
  attacker_name_with_map_position text,
  defender_name_with_map_position text,
  star_scored int,
  destruction_caused double precision,
  attacking_date_time timestamptz,
  attacker_id text,
  cwl_day_uid text,
  data jsonb not null default '{}'::jsonb
);
create index if not exists cwl_attacklog_day_idx on cwl_attacklog(cwl_day_uid, attacking_date_time);
create index if not exists cwl_attacklog_attacker_idx on cwl_attacklog(attacker_id, attacking_date_time desc);

create table if not exists capital_raid_season (
  index_no bigint generated by default as identity primary key,
  generated_uid text not null unique,
  battle_start timestamptz,
  battle_end timestamptz,
  total_loot bigint not null default 0,
  raids_won int not null default 0,
  total_attacks int not null default 0,
  participants_no int not null default 0,
  absentees_no int not null default 0,
  participants_name jsonb not null default '[]'::jsonb,
  absentees_name jsonb not null default '[]'::jsonb,
  data jsonb not null default '{}'::jsonb
);
create index if not exists capital_season_start_idx on capital_raid_season(battle_start desc);

create table if not exists capital_raid_participants (
  index_no bigint generated by default as identity primary key,
  capital_raid_uid text not null,
  player_name text,
  player_id text not null,
  total_attacks int not null default 0,
  total_loot_gained bigint not null default 0,
  capital_raid_attack_uid text,
  capital_raid_start timestamptz,
  capital_raid_end timestamptz,
  data jsonb not null default '{}'::jsonb,
  unique(capital_raid_uid, player_id)
);
create index if not exists capital_participants_player_idx on capital_raid_participants(player_id, capital_raid_end desc);

create table if not exists capital_raid_attacklog (
  index_no bigint generated by default as identity primary key,
  generated_uid text not null unique,
  raid_no int,
  clan_name text,
  district_name text,
  attacker_name text,
  star_scored int,
  destruction_caused double precision,
  loot_gained bigint,
  attacking_date_time timestamptz,
  attacker_id text,
  capital_raid_uid text,
  data jsonb not null default '{}'::jsonb
);
create index if not exists capital_attacklog_raid_idx on capital_raid_attacklog(capital_raid_uid, attacking_date_time);
create index if not exists capital_attacklog_attacker_idx on capital_raid_attacklog(attacker_id, attacking_date_time desc);

create table if not exists ai_chat (
  index_no bigint generated by default as identity primary key,
  date_time timestamptz not null default now(),
  messenger text,
  context jsonb not null default '{}'::jsonb
);

-- Persistent Discord AI state. These rows survive restarts/redeploys.
create table if not exists ai_answers (
  id uuid primary key default gen_random_uuid(),
  guild_id text,
  channel_id text,
  user_id text not null,
  message_id text,
  provider text not null,
  question text not null,
  full_answer text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists ai_answers_user_time_idx on ai_answers(user_id, created_at desc);
create index if not exists ai_answers_expiry_idx on ai_answers(expires_at);

create table if not exists ai_conversations (
  id bigint generated by default as identity primary key,
  guild_id text,
  channel_id text,
  user_id text not null,
  provider text not null,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists ai_conversations_scope_time_idx on ai_conversations(guild_id, channel_id, user_id, created_at desc);
create index if not exists ai_conversations_expiry_idx on ai_conversations(expires_at);

-- Read-only AI retrieval via anon; writes/sync use service_role.
do $$ declare t text; begin
  foreach t in array array['clan_info','clan_info_snap','cw_session','cw_session_participants','cw_attacklog','cwl_seasons','cwl_season_participants','cwl_daywise_attacklog','cwl_attacklog','capital_raid_season','capital_raid_participants','capital_raid_attacklog','ai_chat'] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists "ai read" on %I', t);
    execute format('create policy "ai read" on %I for select to anon using (true)', t);
  end loop;
end $$;

alter table ai_answers enable row level security;
alter table ai_conversations enable row level security;
revoke all on table ai_answers from anon, authenticated;
revoke all on table ai_conversations from anon, authenticated;
grant select, insert, update, delete on table ai_answers to service_role;
grant select, insert, update, delete on table ai_conversations to service_role;
