-- Ensure the normal Clan War detail table exists in databases where the
-- original schema was not fully applied. Safe to run multiple times.

begin;

create table if not exists war_attacks (
  id bigint generated by default as identity primary key,
  war_key text not null,
  clan_tag text not null,
  attacker_tag text not null,
  attacker_name text,
  defender_tag text,
  defender_name text,
  stars int,
  destruction_percentage double precision,
  order_no int,
  duration_seconds int,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique(war_key, clan_tag, attacker_tag, order_no)
);

create index if not exists war_attacks_war_idx on war_attacks(war_key, order_no);
create index if not exists war_attacks_attacker_idx on war_attacks(attacker_tag, observed_at desc);

alter table war_attacks enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'war_attacks'
      and policyname = 'ai read war attacks'
  ) then
    create policy "ai read war attacks"
      on war_attacks for select to anon using (true);
  end if;
end
$$;

commit;
