-- Run this in the NEW Discord Supabase project before deploying the new sync service.
-- Existing attack_log rows are preserved into their appropriate tables, then the
-- mixed table is removed.

create table if not exists cwl_attacks (
  id bigint generated by default as identity primary key,
  season_key text not null,
  war_tag text not null,
  round_no int not null default 0,
  clan_tag text not null,
  attacker_tag text not null,
  attacker_name text,
  defender_tag text,
  defender_name text,
  stars int,
  destruction_percentage double precision,
  order_no int,
  duration_seconds int,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique(war_tag, clan_tag, attacker_tag, order_no)
);

create table if not exists capital_attacks (
  id bigint generated by default as identity primary key,
  season_key text not null,
  clan_tag text not null,
  opponent_clan_tag text,
  opponent_clan_name text,
  attacker_tag text not null,
  attacker_name text,
  district_id int,
  district_name text,
  attack_number int not null,
  stars int,
  destruction_percentage double precision,
  duration_seconds int,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique(season_key, attacker_tag, district_id, attack_number, opponent_clan_tag)
);

-- Migrate existing mixed rows where possible.
insert into cwl_attacks (
  season_key, war_tag, round_no, clan_tag, attacker_tag, attacker_name,
  defender_tag, defender_name, stars, destruction_percentage, order_no,
  duration_seconds, attack_time, observed_at, data
)
select
  season_key,
  tournament_id,
  0,
  clan_tag,
  attacker_tag,
  attacker_name,
  defender_tag,
  defender_name,
  stars,
  destruction_percentage,
  order_no,
  duration_seconds,
  attack_time,
  observed_at,
  data
from attack_log
where tournament_type = 'cwl'
on conflict (war_tag, clan_tag, attacker_tag, order_no) do nothing;

insert into capital_attacks (
  season_key, clan_tag, opponent_clan_tag, opponent_clan_name,
  attacker_tag, attacker_name, district_id, district_name, attack_number,
  stars, destruction_percentage, duration_seconds, attack_time, observed_at, data
)
select
  season_key,
  clan_tag,
  opponent_clan_tag,
  opponent_clan_name,
  attacker_tag,
  attacker_name,
  district_id,
  district_name,
  coalesce(attack_number, 1),
  stars,
  destruction_percentage,
  duration_seconds,
  attack_time,
  observed_at,
  data
from attack_log
where tournament_type = 'capital'
on conflict (season_key, attacker_tag, district_id, attack_number, opponent_clan_tag) do nothing;

-- Normal war attack rows already have a proper destination: war_attacks.
-- Do not migrate them into another table.

drop table if exists attack_log;

create index if not exists cwl_attacks_season_idx on cwl_attacks(season_key, round_no);
create index if not exists cwl_attacks_attacker_idx on cwl_attacks(attacker_tag, observed_at desc);
create index if not exists capital_attacks_season_idx on capital_attacks(season_key, observed_at desc);
create index if not exists capital_attacks_attacker_idx on capital_attacks(attacker_tag, observed_at desc);
create index if not exists capital_attacks_opponent_idx on capital_attacks(opponent_clan_tag, observed_at desc);

alter table cwl_attacks enable row level security;
alter table capital_attacks enable row level security;

create policy "ai read cwl attacks" on cwl_attacks for select to anon using (true);
create policy "ai read capital attacks" on capital_attacks for select to anon using (true);
