-- Adds the sync_runs table used by the sync layer for run/error logging.
-- Safe to run on an existing Ponyo database.

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  job text not null,
  status text not null,
  details jsonb,
  message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists idx_sync_runs_job_time on public.sync_runs(job, started_at desc);
alter table public.sync_runs enable row level security;
