-- SAFE MIGRATION
-- Creates tournament-specific attack tables, copies old attack_log data,
-- verifies the copy, then removes the obsolete mixed table in one transaction.
--
-- IMPORTANT: if this migration fails at any point, the transaction rolls back.

begin;

create table if not exists cwl_attacks (
  id bigint generated by default as identity primary key,
  season_key text not null,
  war_tag text not null,
  round_no int not null default 0,
  clan_tag text not null,
  attacker_tag text not null,
  attacker_name text,
  defender_tag text,
  defender_name text,
  stars int,
  destruction_percentage double precision,
  order_no int,
  duration_seconds int,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique(war_tag, clan_tag, attacker_tag, order_no)
);

create table if not exists capital_attacks (
  id bigint generated by default as identity primary key,
  season_key text not null,
  clan_tag text not null,
  opponent_clan_tag text,
  opponent_clan_name text,
  attacker_tag text not null,
  attacker_name text,
  district_id int,
  district_name text,
  attack_number int not null,
  stars int,
  destruction_percentage double precision,
  duration_seconds int,
  attack_time timestamptz,
  observed_at timestamptz not null default now(),
  data jsonb not null,
  unique(season_key, attacker_tag, district_id, attack_number, opponent_clan_tag)
);

-- Existing Capital district_id was stored as text in attack_log.
-- Convert numeric IDs to integer; non-numeric values become NULL.
-- If attack_number was missing, use a deterministic row number within the
-- attacker/district/opponent group instead of making every old row attack #1.
insert into cwl_attacks (
  season_key, war_tag, round_no, clan_tag, attacker_tag, attacker_name,
  defender_tag, defender_name, stars, destruction_percentage, order_no,
  duration_seconds, attack_time, observed_at, data
)
select
  coalesce(season_key, tournament_id),
  tournament_id,
  0,
  clan_tag,
  attacker_tag,
  attacker_name,
  defender_tag,
  defender_name,
  stars,
  destruction_percentage,
  order_no,
  duration_seconds,
  attack_time,
  observed_at,
  data
from attack_log
where tournament_type = 'cwl'
on conflict (war_tag, clan_tag, attacker_tag, order_no) do nothing;

with capital_source as (
  select
    a.*,
    case
      when a.attack_number is not null then a.attack_number
      else row_number() over (
        partition by a.season_key, a.attacker_tag, a.district_id, a.opponent_clan_tag
        order by a.observed_at, a.id
      )::int
    end as migrated_attack_number,
    case
      when a.district_id::text ~ '^\d+$' then a.district_id::text::int
      else null
    end as migrated_district_id
  from attack_log a
  where a.tournament_type = 'capital'
)
insert into capital_attacks (
  season_key, clan_tag, opponent_clan_tag, opponent_clan_name,
  attacker_tag, attacker_name, district_id, district_name, attack_number,
  stars, destruction_percentage, duration_seconds, attack_time, observed_at, data
)
select
  season_key,
  clan_tag,
  opponent_clan_tag,
  opponent_clan_name,
  attacker_tag,
  attacker_name,
  migrated_district_id,
  district_name,
  migrated_attack_number,
  stars,
  destruction_percentage,
  duration_seconds,
  attack_time,
  observed_at,
  data
from capital_source
on conflict (season_key, attacker_tag, district_id, attack_number, opponent_clan_tag) do nothing;

-- Verify every old CWL row has a matching new row.
do $$
begin
  if exists (
    select 1
    from attack_log a
    where a.tournament_type = 'cwl'
      and not exists (
        select 1
        from cwl_attacks c
        where c.war_tag = a.tournament_id
          and c.clan_tag = a.clan_tag
          and c.attacker_tag = a.attacker_tag
          and c.order_no is not distinct from a.order_no
      )
  ) then
    raise exception 'CWL migration verification failed';
  end if;

  -- Verify Capital rows by their migrated identity. Numeric district IDs are
  -- compared as integers; non-numeric district IDs are intentionally NULL.
  if exists (
    with capital_source as (
      select
        a.*,
        case
          when a.attack_number is not null then a.attack_number
          else row_number() over (
            partition by a.season_key, a.attacker_tag, a.district_id, a.opponent_clan_tag
            order by a.observed_at, a.id
          )::int
        end as migrated_attack_number,
        case
          when a.district_id::text ~ '^\d+$' then a.district_id::text::int
          else null
        end as migrated_district_id
      from attack_log a
      where a.tournament_type = 'capital'
    )
    select 1
    from capital_source a
    where not exists (
      select 1
      from capital_attacks c
      where c.season_key = a.season_key
        and c.clan_tag = a.clan_tag
        and c.attacker_tag = a.attacker_tag
        and c.district_id is not distinct from a.migrated_district_id
        and c.attack_number = a.migrated_attack_number
        and c.opponent_clan_tag is not distinct from a.opponent_clan_tag
    )
  ) then
    raise exception 'Capital migration verification failed';
  end if;
end
$$;

drop table attack_log;

create index if not exists cwl_attacks_season_idx on cwl_attacks(season_key, round_no);
create index if not exists cwl_attacks_attacker_idx on cwl_attacks(attacker_tag, observed_at desc);
create index if not exists capital_attacks_season_idx on capital_attacks(season_key, observed_at desc);
create index if not exists capital_attacks_attacker_idx on capital_attacks(attacker_tag, observed_at desc);
create index if not exists capital_attacks_opponent_idx on capital_attacks(opponent_clan_tag, observed_at desc);

alter table cwl_attacks enable row level security;
alter table capital_attacks enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'cwl_attacks'
      and policyname = 'ai read cwl attacks'
  ) then
    create policy "ai read cwl attacks"
      on cwl_attacks for select to anon using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'capital_attacks'
      and policyname = 'ai read capital attacks'
  ) then
    create policy "ai read capital attacks"
      on capital_attacks for select to anon using (true);
  end if;
end
$$;

commit;
